services:
  mc-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    environment:
      MEMORY_MIN: "1G"
      MEMORY_MAX: "2G"
    ports:
      - "8888:25565"
    volumes:
      - mc_data:/data
    restart: unless-stopped
    stop_grace_period: 1m

volumes:
  mc_data: